name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install black isort flake8 flake8-bugbear mypy
      - name: Run black
        run: black --check tiledb
      - name: Run isort
        run: isort --check tiledb
      - name: Run flake8
        run: flake8 tiledb
      - name: Run mypy
        run: mypy tiledb
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install this package
        run: pip install -e .
      - name: Install pytest
        run: pip install pytest pytest-coverage
      - name: Run tests
        run: pytest tests
